require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/cinema_halls", type: :request do
  
  # CinemaHall. As you add validations to CinemaHall, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      CinemaHall.create! valid_attributes
      get cinema_halls_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      cinema_hall = CinemaHall.create! valid_attributes
      get cinema_hall_url(cinema_hall)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_cinema_hall_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      cinema_hall = CinemaHall.create! valid_attributes
      get edit_cinema_hall_url(cinema_hall)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new CinemaHall" do
        expect {
          post cinema_halls_url, params: { cinema_hall: valid_attributes }
        }.to change(CinemaHall, :count).by(1)
      end

      it "redirects to the created cinema_hall" do
        post cinema_halls_url, params: { cinema_hall: valid_attributes }
        expect(response).to redirect_to(cinema_hall_url(CinemaHall.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new CinemaHall" do
        expect {
          post cinema_halls_url, params: { cinema_hall: invalid_attributes }
        }.to change(CinemaHall, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post cinema_halls_url, params: { cinema_hall: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested cinema_hall" do
        cinema_hall = CinemaHall.create! valid_attributes
        patch cinema_hall_url(cinema_hall), params: { cinema_hall: new_attributes }
        cinema_hall.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the cinema_hall" do
        cinema_hall = CinemaHall.create! valid_attributes
        patch cinema_hall_url(cinema_hall), params: { cinema_hall: new_attributes }
        cinema_hall.reload
        expect(response).to redirect_to(cinema_hall_url(cinema_hall))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        cinema_hall = CinemaHall.create! valid_attributes
        patch cinema_hall_url(cinema_hall), params: { cinema_hall: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested cinema_hall" do
      cinema_hall = CinemaHall.create! valid_attributes
      expect {
        delete cinema_hall_url(cinema_hall)
      }.to change(CinemaHall, :count).by(-1)
    end

    it "redirects to the cinema_halls list" do
      cinema_hall = CinemaHall.create! valid_attributes
      delete cinema_hall_url(cinema_hall)
      expect(response).to redirect_to(cinema_halls_url)
    end
  end
end
