#  require 'rails_helper'

# # This spec was generated by rspec-rails when you ran the scaffold generator.
# # It demonstrates how one might use RSpec to test the controller code that
# # was generated by Rails when you ran the scaffold generator.
# #
# # It assumes that the implementation code is generated by the rails scaffold
# # generator. If you are using any extension libraries to generate different
# # controller code, this generated spec may or may not pass.
# #
# # It only uses APIs available in rails and/or rspec-rails. There are a number
# # of tools you can use to make these specs even more expressive, but we're
# # sticking to rails and rspec-rails APIs to keep things simple and stable.

# RSpec.describe "/seats", type: :request do
  
#   # Seat. As you add validations to Seat, be sure to
#   # adjust the attributes here as well.
#   let(:valid_attributes) {
#     skip("Add a hash of attributes valid for your model")
#   }

#   let(:invalid_attributes) {
#     skip("Add a hash of attributes invalid for your model")
#   }

#   describe "GET /index" do
#     it "renders a successful response" do
#       Seat.create! valid_attributes
#       get seats_url
#       expect(response).to be_successful
#     end
#   end

#   describe "GET /show" do
#     it "renders a successful response" do
#       seat = Seat.create! valid_attributes
#       get seat_url(seat)
#       expect(response).to be_successful
#     end
#   end

#   describe "GET /new" do
#     it "renders a successful response" do
#       get new_seat_url
#       expect(response).to be_successful
#     end
#   end

#   describe "GET /edit" do
#     it "render a successful response" do
#       seat = Seat.create! valid_attributes
#       get edit_seat_url(seat)
#       expect(response).to be_successful
#     end
#   end

#   describe "POST /create" do
#     context "with valid parameters" do
#       it "creates a new Seat" do
#         expect {
#           post seats_url, params: { seat: valid_attributes }
#         }.to change(Seat, :count).by(1)
#       end

#       it "redirects to the created seat" do
#         post seats_url, params: { seat: valid_attributes }
#         expect(response).to redirect_to(seat_url(Seat.last))
#       end
#     end

#     context "with invalid parameters" do
#       it "does not create a new Seat" do
#         expect {
#           post seats_url, params: { seat: invalid_attributes }
#         }.to change(Seat, :count).by(0)
#       end

#       it "renders a successful response (i.e. to display the 'new' template)" do
#         post seats_url, params: { seat: invalid_attributes }
#         expect(response).to be_successful
#       end
#     end
#   end

#   describe "PATCH /update" do
#     context "with valid parameters" do
#       let(:new_attributes) {
#         skip("Add a hash of attributes valid for your model")
#       }

#       it "updates the requested seat" do
#         seat = Seat.create! valid_attributes
#         patch seat_url(seat), params: { seat: new_attributes }
#         seat.reload
#         skip("Add assertions for updated state")
#       end

#       it "redirects to the seat" do
#         seat = Seat.create! valid_attributes
#         patch seat_url(seat), params: { seat: new_attributes }
#         seat.reload
#         expect(response).to redirect_to(seat_url(seat))
#       end
#     end

#     context "with invalid parameters" do
#       it "renders a successful response (i.e. to display the 'edit' template)" do
#         seat = Seat.create! valid_attributes
#         patch seat_url(seat), params: { seat: invalid_attributes }
#         expect(response).to be_successful
#       end
#     end
#   end

#   describe "DELETE /destroy" do
#     it "destroys the requested seat" do
#       seat = Seat.create! valid_attributes
#       expect {
#         delete seat_url(seat)
#       }.to change(Seat, :count).by(-1)
#     end

#     it "redirects to the seats list" do
#       seat = Seat.create! valid_attributes
#       delete seat_url(seat)
#       expect(response).to redirect_to(seats_url)
#     end
#   end
# end
