default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout:

development:
  <<: *default
  database: demon_cinema_development
  host: localhost
  username: demon_cinema
  password: development1
