default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout:

development:
  <<: *default
  database: demon_cinema_development
  host: localhost
  username: demon_cinema
  password: <%= ENV['DEMON_CINEMA_DEVELOPMENT_DB_PASS'] %>
